server:
  port: 7777

eureka:
  instance:
    hostname: localhost
    appname: EurekaRegisterCenter
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/EurekaRegisterCenter/eureka/